model_path: models/layout_cdla.onnx

use_cuda: false
CUDAExecutionProvider:
    device_id: 0
    arena_extend_strategy: kNextPowerOfTwo
    cudnn_conv_algo_search: EXHAUSTIVE
    do_copy_in_default_stream: true

pre_process:
    Resize:
        size: [800, 608]
    NormalizeImage:
        std: [0.229, 0.224, 0.225]
        mean: [0.485, 0.456, 0.406]
        scale: 1./255.
        order: hwc
    ToCHWImage:
    KeepKeys:
        keep_keys: ['image']

post_process:
    score_threshold: 0.5
    nms_threshold: 0.5