model_path: models/ch_PP-OCRv4_rec_infer.onnx

use_cuda: false
# Details of the params: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
CUDAExecutionProvider:
    device_id: 0
    arena_extend_strategy: kNextPowerOfTwo
    cudnn_conv_algo_search: EXHAUSTIVE
    do_copy_in_default_stream: true

rec_img_shape: [3, 48, 320]
rec_batch_num: 6
