name: Push rapidocr_onnxruntime to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'python/rapidocr_onnxruntime/**'
      - 'docs/doc_whl_rapidocr_ort.md'
      - 'python/setup_onnxruntime.py'

env:
  RESOURCES_URL: https://github.com/RapidAI/RapidOCR/releases/download/v1.1.0/required_for_whl_v1.1.0.zip

jobs:
  UnitTesting:
    runs-on: windows-latest
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Download required_for_whl_v1.1.0
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile3  # Remember to give an ID if you need the output filename
        with:
            url: https://github.com/RapidAI/RapidOCR/releases/download/v1.1.0/required_for_whl_v1.1.0.zip
            target: ./

      - name: Decompress
        shell: powershell
        run: |
              Expand-7Zip -ArchiveFileName ./required_for_whl_v1.1.0.zip -TargetPath .\

      - name: List all file
        shell: cmd
        run:  |
              dir .

      - name: Unit testings
        shell: cmd
        run: |
          set git_keep_path=%cur_dir%\python\resoureces\models\.gitkeep
          del %git_keep_path%
          copy required_for_whl_v1.1.0\resources\models\* python\rapidocr_onnxruntime\models\
          copy required_for_whl_v1.1.0\resources\models\* python\rapidocr_openvino\models\
          cd python
          pip install -r requirements.txt
          pip install onnxruntime==1.11.0 openvino==2022.2.0
          cd tests
          pytest test_det.py test_cls.py test_rec.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set SSH Environment
        env:
          DEPLOY_KEYS: ${{ secrets.GEN_PYTHON_SDK }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

      - name: Download models
        run: |
          cd python
          wget $RESOURCES_URL
          unzip required_for_whl_v1.1.0.zip
          cp required_for_whl_v1.1.0/resources/models/*.onnx rapidocr_onnxruntime/models

      - name: Run setup_onnxruntime.py
        run: |
          cd python
          mkdir rapidocr_onnxruntime_t
          mv rapidocr_onnxruntime rapidocr_onnxruntime_t
          mv rapidocr_onnxruntime_t rapidocr_onnxruntime
          cd rapidocr_onnxruntime
          echo "from .rapidocr_onnxruntime.rapid_ocr_api import RapidOCR" > __init__.py

          cd ..
          python -m pip install --upgrade pip
          python setup_onnxruntime.py bdist_wheel ${{ github.event.head_commit.message }}
          mv dist ../

      # - name: Publish distribution ðŸ“¦ to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.5.0
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: dist/

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
