name: Push rapidocr_paddle to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'python/rapidocr_paddle/**'
      - 'docs/doc_whl_rapidocr_paddle.md'
      - 'python/setup_paddle.py'
      - '.github/workflows/gen_whl_to_pypi_rapidocr_paddle.yml'
      - 'python/requirements_paddle.txt'
    # tags:
    #   - v*

env:
  RESOURCES_URL: https://github.com/RapidAI/RapidOCR/releases/download/v1.1.0/paddle_models_v4.zip

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Unit testings
        run: |
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $DIR_NAME
          cp -r models/* python/rapidocr_paddle/models/
          cd python
          pip install -r requirements_paddle.txt
          pip install pytest wheel get_pypi_latest_version paddlepaddle
          cd tests
          pytest test_paddle.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Set SSH Environment
        env:
          DEPLOY_KEYS: ${{ secrets.GEN_PYTHON_SDK }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

      - name: Download models
        run: |
          cd python
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $ZIP_NAME
          cp -r models/* rapidocr_paddle/models

      - name: Run setup_paddle.py
        run: |
          cd python
          pip install setuptools get_pypi_latest_version wheel

          mkdir rapidocr_paddle_t
          mv rapidocr_paddle rapidocr_paddle_t
          mv rapidocr_paddle_t rapidocr_paddle
          cd rapidocr_paddle
          echo "from .rapidocr_paddle.main import RapidOCR, VisRes" > __init__.py

          cd ..
          python -m pip install --upgrade pip

          echo "${{ github.event.head_commit.message }}"
          python setup_paddle.py bdist_wheel "${{ github.event.head_commit.message }}"
          mv dist ../

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPIDOCR_OPENVINO }}
          packages_dir: dist/
