name: Push rapidocr_api to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'api/rapidocr_api/**'
      - 'docs/doc_whl_rapidocr_api.md'
      - 'api/setup.py'
      - '.github/workflows/gen_whl_to_pypi_rapidocr_api.yml'
      - 'api/requirements.txt'

jobs:
  GenerateWHL_PushPyPi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set SSH Environment
        env:
          DEPLOY_KEYS: ${{ secrets.GEN_PYTHON_SDK }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

      - name: Run setup.py
        run: |
          cd api
          pip install -r requirements.txt
          pip install get_pypi_latest_version wheel

          python -m pip install --upgrade pip
          python setup.py bdist_wheel "${{ github.event.head_commit.message }}"

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPIDOCR_API_PYPI }}
          packages_dir: api/dist/
