name: Push rapidocr_openvino to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'python/rapidocr_openvino/**'
      - 'docs/doc_whl_rapidocr_vino.md'
      - 'python/setup_openvino.py'
      - '.github/workflows/gen_whl_to_pypi_rapidocr_vino.yml'

env:
  RESOURCES_URL: https://github.com/RapidAI/RapidOCR/releases/download/v1.1.0/required_for_whl_v1.1.0.zip

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Unit testings
        run: |
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $DIR_NAME
          cp $DIR_NAME/resources/models/*.onnx python/rapidocr_onnxruntime/models/
          cp $DIR_NAME/resources/models/*.onnx python/rapidocr_openvino/models/
          cd python
          pip install -r requirements.txt
          cd tests
          pytest test_det.py test_cls.py test_rec.py test_all_vino.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Set SSH Environment
        env:
          DEPLOY_KEYS: ${{ secrets.GEN_PYTHON_SDK }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

      - name: Download models
        run: |
          cd python
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $ZIP_NAME
          cp $DIR_NAME/resources/models/*.onnx rapidocr_openvino/models

      - name: Run setup_openvino.py
        run: |
          cd python
          pip install -r requirements.txt
          mkdir rapidocr_openvino_t
          mv rapidocr_openvino rapidocr_openvino_t
          mv rapidocr_openvino_t rapidocr_openvino
          cd rapidocr_openvino
          echo "from .rapidocr_openvino.rapid_ocr_api import RapidOCR" > __init__.py

          cd ..
          python -m pip install --upgrade pip
          python setup_openvino.py bdist_wheel ${{ github.event.head_commit.message }}
          mv dist ../

      # - name: Publish distribution ðŸ“¦ to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.5.0
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: dist/

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPIDOCR_OPENVINO }}
          packages_dir: dist/
