name: SyncToGitee
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: 'github/RapidAI'
          dst: 'gitee/RapidAI'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          force_update: true
          # only sync this repo
          static_list: "RapidOCR"
          debug: true
